apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi-jax-train-64node-czhenguo
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 20
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: 621547421844.dkr.ecr.us-east-2.amazonaws.com/eks_trn2_axlearn:axlearn_neuronx-czhenguo
             name: mpitest
             imagePullPolicy: Always
             env:
               - name: POD_UID
                 value: "92515762-d9bd-4c79-91cb-6dc82d0e59da"
               - name: NUM_NODES
                 value: "64"
               - name: TP_DEGREE
                 value: "4"
               - name: NUM_LAYERS
                 value: "80"
             command:
             - mpirun
             - --allow-run-as-root
             - --tag-output
             - -np
             - "64"  # should be equal to number of trn nodes
             - -bind-to
             - none
             - -map-by
             - slot
             - -x
             - POD_UID
             - -x
             - NUM_NODES
             - -x
             - TP_DEGREE
             - -x
             - NUM_LAYERS
             - -x
             - PROJECT_PATH
             - -x
             - MLFLOW_TRACKING_URI
             - -wdir
             - /neuron/
             - /neuron/run_trainer_multinode.sh
           initContainers:
           - name: wait-hostfilename
             image: 621547421844.dkr.ecr.us-east-2.amazonaws.com/eks_trn2_axlearn:axlearn_neuronx-czhenguo
             command:
             - bash
             - -cx
             - "[[ $(cat /etc/mpi/discover_hosts.sh | wc -l) != 1 ]] && (date; echo Ready; cat /etc/mpi/discover_hosts.sh) || (date; echo 'not ready ...'; sleep 5; exit 1) && while read host; do while ! ssh $host echo $host ; do date; echo \"Pod $host is not up ...\"; sleep 5; done; date; echo \"Pod $host is ready\"; done <<< \"$(/etc/mpi/discover_hosts.sh)\""
             volumeMounts:
             - mountPath: /etc/mpi
               name: mpi-job-config
             - mountPath: /root/.ssh
               name: ssh-auth

    Worker:
      replicas: 64  # should be equal to number of trn nodes
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                    - trn2.48xlarge
          containers:
          - image: 621547421844.dkr.ecr.us-east-2.amazonaws.com/eks_trn2_axlearn:axlearn_neuronx-czhenguo
            name: mpitest
            imagePullPolicy: Always
            resources:
              limits:
                aws.amazon.com/neuron: "16"
                vpc.amazonaws.com/efa: "16"
              requests:
                aws.amazon.com/neuron: "16"
                vpc.amazonaws.com/efa: "16"
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /shared
              name: persistent-storage
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: ktf-pvc3

